// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: articles.sql

package queries

import (
	"context"
)

const countArticles = `-- name: CountArticles :one
SELECT COUNT(*)
FROM articles
WHERE status = 'published'
  AND deleted_at IS NULL
`

func (q *Queries) CountArticles(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countArticles)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getArticleBySlug = `-- name: GetArticleBySlug :one
SELECT id, slug, title, excerpt, content, cover_image_url, type, status, source_name, source_url, seo_title, seo_description, is_featured, author_id, published_at, created_at, updated_at, deleted_at
FROM articles
WHERE slug = $1
  AND status = 'published'
  AND deleted_at IS NULL
`

func (q *Queries) GetArticleBySlug(ctx context.Context, slug string) (Article, error) {
	row := q.db.QueryRow(ctx, getArticleBySlug, slug)
	var i Article
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Excerpt,
		&i.Content,
		&i.CoverImageUrl,
		&i.Type,
		&i.Status,
		&i.SourceName,
		&i.SourceUrl,
		&i.SeoTitle,
		&i.SeoDescription,
		&i.IsFeatured,
		&i.AuthorID,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listArticles = `-- name: ListArticles :many
SELECT id, slug, title, excerpt, content, cover_image_url, type, status, source_name, source_url, seo_title, seo_description, is_featured, author_id, published_at, created_at, updated_at, deleted_at
FROM articles
WHERE status = 'published'
  AND deleted_at IS NULL
ORDER BY published_at DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type ListArticlesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error) {
	rows, err := q.db.Query(ctx, listArticles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Article{}
	for rows.Next() {
		var i Article
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Excerpt,
			&i.Content,
			&i.CoverImageUrl,
			&i.Type,
			&i.Status,
			&i.SourceName,
			&i.SourceUrl,
			&i.SeoTitle,
			&i.SeoDescription,
			&i.IsFeatured,
			&i.AuthorID,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
