// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: catalog.sql

package queries

import (
	"context"
)

const countCourses = `-- name: CountCourses :one
SELECT COUNT(*)
FROM courses
WHERE deleted_at IS NULL
`

func (q *Queries) CountCourses(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCourses)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUniversities = `-- name: CountUniversities :one
SELECT COUNT(*)
FROM universities
WHERE deleted_at IS NULL
`

func (q *Queries) CountUniversities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUniversities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCourseBySlug = `-- name: GetCourseBySlug :one
SELECT id, slug, university_id, name, area, level, regime, duration_years, annual_fee, entry_requirements, created_at, updated_at, deleted_at
FROM courses
WHERE slug = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetCourseBySlug(ctx context.Context, slug string) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseBySlug, slug)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.UniversityID,
		&i.Name,
		&i.Area,
		&i.Level,
		&i.Regime,
		&i.DurationYears,
		&i.AnnualFee,
		&i.EntryRequirements,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUniversityBySlug = `-- name: GetUniversityBySlug :one
SELECT id, slug, name, type, province, description, logo_url, website, email, phone, verified, verified_at, created_by, created_at, updated_at, deleted_at
FROM universities
WHERE slug = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUniversityBySlug(ctx context.Context, slug string) (University, error) {
	row := q.db.QueryRow(ctx, getUniversityBySlug, slug)
	var i University
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Type,
		&i.Province,
		&i.Description,
		&i.LogoUrl,
		&i.Website,
		&i.Email,
		&i.Phone,
		&i.Verified,
		&i.VerifiedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCourses = `-- name: ListCourses :many
SELECT id, slug, university_id, name, area, level, regime, duration_years, annual_fee, entry_requirements, created_at, updated_at, deleted_at
FROM courses
WHERE deleted_at IS NULL
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListCoursesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCourses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.UniversityID,
			&i.Name,
			&i.Area,
			&i.Level,
			&i.Regime,
			&i.DurationYears,
			&i.AnnualFee,
			&i.EntryRequirements,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUniversities = `-- name: ListUniversities :many
SELECT id, slug, name, type, province, description, logo_url, website, email, phone, verified, verified_at, created_by, created_at, updated_at, deleted_at
FROM universities
WHERE deleted_at IS NULL
ORDER BY name ASC
LIMIT $1 OFFSET $2
`

type ListUniversitiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUniversities(ctx context.Context, arg ListUniversitiesParams) ([]University, error) {
	rows, err := q.db.Query(ctx, listUniversities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []University{}
	for rows.Next() {
		var i University
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Type,
			&i.Province,
			&i.Description,
			&i.LogoUrl,
			&i.Website,
			&i.Email,
			&i.Phone,
			&i.Verified,
			&i.VerifiedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
