// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mentorship.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMentors = `-- name: CountMentors :one
SELECT COUNT(*)
FROM mentor_profiles mp
JOIN users u ON u.id = mp.user_id
WHERE mp.deleted_at IS NULL
  AND u.deleted_at IS NULL
  AND u.role = 'mentor'
  AND mp.is_active = TRUE
`

func (q *Queries) CountMentors(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMentors)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMentorshipSession = `-- name: CreateMentorshipSession :one
INSERT INTO mentorship_sessions (
  mentor_id,
  requester_id,
  message,
  status,
  scheduled_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, mentor_id, requester_id, message, status, scheduled_at, created_at, updated_at, deleted_at
`

type CreateMentorshipSessionParams struct {
	MentorID    pgtype.UUID        `json:"mentor_id"`
	RequesterID pgtype.UUID        `json:"requester_id"`
	Message     string             `json:"message"`
	Status      string             `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
}

func (q *Queries) CreateMentorshipSession(ctx context.Context, arg CreateMentorshipSessionParams) (MentorshipSession, error) {
	row := q.db.QueryRow(ctx, createMentorshipSession,
		arg.MentorID,
		arg.RequesterID,
		arg.Message,
		arg.Status,
		arg.ScheduledAt,
	)
	var i MentorshipSession
	err := row.Scan(
		&i.ID,
		&i.MentorID,
		&i.RequesterID,
		&i.Message,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMentorByID = `-- name: GetMentorByID :one
SELECT
  mp.id,
  mp.user_id,
  mp.headline,
  mp.bio,
  mp.expertise,
  mp.availability,
  mp.is_active,
  mp.created_at,
  mp.updated_at,
  mp.deleted_at,
  u.id AS user_id,
  u.email,
  u.password_hash,
  u.role,
  u.name,
  u.avatar_url,
  u.created_at,
  u.updated_at,
  u.deleted_at
FROM mentor_profiles mp
JOIN users u ON u.id = mp.user_id
WHERE mp.user_id = $1
  AND mp.deleted_at IS NULL
  AND u.deleted_at IS NULL
  AND u.role = 'mentor'
  AND mp.is_active = TRUE
`

type GetMentorByIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Headline     string             `json:"headline"`
	Bio          string             `json:"bio"`
	Expertise    string             `json:"expertise"`
	Availability pgtype.Text        `json:"availability"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	UserID_2     pgtype.UUID        `json:"user_id_2"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Name         string             `json:"name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CreatedAt_2  pgtype.Timestamptz `json:"created_at_2"`
	UpdatedAt_2  pgtype.Timestamptz `json:"updated_at_2"`
	DeletedAt_2  pgtype.Timestamptz `json:"deleted_at_2"`
}

func (q *Queries) GetMentorByID(ctx context.Context, userID pgtype.UUID) (GetMentorByIDRow, error) {
	row := q.db.QueryRow(ctx, getMentorByID, userID)
	var i GetMentorByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Headline,
		&i.Bio,
		&i.Expertise,
		&i.Availability,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.UserID_2,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Name,
		&i.AvatarUrl,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
		&i.DeletedAt_2,
	)
	return i, err
}

const listMentors = `-- name: ListMentors :many
SELECT
  mp.id,
  mp.user_id,
  mp.headline,
  mp.bio,
  mp.expertise,
  mp.availability,
  mp.is_active,
  mp.created_at,
  mp.updated_at,
  mp.deleted_at,
  u.id AS user_id,
  u.email,
  u.password_hash,
  u.role,
  u.name,
  u.avatar_url,
  u.created_at,
  u.updated_at,
  u.deleted_at
FROM mentor_profiles mp
JOIN users u ON u.id = mp.user_id
WHERE mp.deleted_at IS NULL
  AND u.deleted_at IS NULL
  AND u.role = 'mentor'
  AND mp.is_active = TRUE
ORDER BY u.name ASC
LIMIT $1 OFFSET $2
`

type ListMentorsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListMentorsRow struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Headline     string             `json:"headline"`
	Bio          string             `json:"bio"`
	Expertise    string             `json:"expertise"`
	Availability pgtype.Text        `json:"availability"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	UserID_2     pgtype.UUID        `json:"user_id_2"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	Name         string             `json:"name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CreatedAt_2  pgtype.Timestamptz `json:"created_at_2"`
	UpdatedAt_2  pgtype.Timestamptz `json:"updated_at_2"`
	DeletedAt_2  pgtype.Timestamptz `json:"deleted_at_2"`
}

func (q *Queries) ListMentors(ctx context.Context, arg ListMentorsParams) ([]ListMentorsRow, error) {
	rows, err := q.db.Query(ctx, listMentors, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMentorsRow{}
	for rows.Next() {
		var i ListMentorsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Headline,
			&i.Bio,
			&i.Expertise,
			&i.Availability,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserID_2,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.Name,
			&i.AvatarUrl,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.DeletedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
