// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID             pgtype.UUID        `json:"id"`
	Slug           string             `json:"slug"`
	Title          string             `json:"title"`
	Excerpt        pgtype.Text        `json:"excerpt"`
	Content        string             `json:"content"`
	CoverImageUrl  pgtype.Text        `json:"cover_image_url"`
	Type           string             `json:"type"`
	Status         string             `json:"status"`
	SourceName     pgtype.Text        `json:"source_name"`
	SourceUrl      pgtype.Text        `json:"source_url"`
	SeoTitle       pgtype.Text        `json:"seo_title"`
	SeoDescription pgtype.Text        `json:"seo_description"`
	IsFeatured     bool               `json:"is_featured"`
	AuthorID       pgtype.UUID        `json:"author_id"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type AuthActionToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Purpose    string             `json:"purpose"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Course struct {
	ID                pgtype.UUID        `json:"id"`
	Slug              string             `json:"slug"`
	UniversityID      pgtype.UUID        `json:"university_id"`
	Name              string             `json:"name"`
	Area              string             `json:"area"`
	Level             string             `json:"level"`
	Regime            string             `json:"regime"`
	DurationYears     pgtype.Int4        `json:"duration_years"`
	AnnualFee         pgtype.Numeric     `json:"annual_fee"`
	EntryRequirements pgtype.Text        `json:"entry_requirements"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type MentorProfile struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Headline     string             `json:"headline"`
	Bio          string             `json:"bio"`
	Expertise    string             `json:"expertise"`
	Availability pgtype.Text        `json:"availability"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type MentorshipSession struct {
	ID          pgtype.UUID        `json:"id"`
	MentorID    pgtype.UUID        `json:"mentor_id"`
	RequesterID pgtype.UUID        `json:"requester_id"`
	Message     string             `json:"message"`
	Status      string             `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Opportunity struct {
	ID           pgtype.UUID        `json:"id"`
	Slug         string             `json:"slug"`
	Title        string             `json:"title"`
	Type         string             `json:"type"`
	EntityName   string             `json:"entity_name"`
	Description  string             `json:"description"`
	Requirements pgtype.Text        `json:"requirements"`
	Deadline     pgtype.Timestamptz `json:"deadline"`
	ApplyUrl     pgtype.Text        `json:"apply_url"`
	Country      string             `json:"country"`
	Language     pgtype.Text        `json:"language"`
	Area         pgtype.Text        `json:"area"`
	IsActive     bool               `json:"is_active"`
	PublishedBy  pgtype.UUID        `json:"published_by"`
	Verified     bool               `json:"verified"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Report struct {
	ID         pgtype.UUID        `json:"id"`
	ReporterID pgtype.UUID        `json:"reporter_id"`
	EntityType string             `json:"entity_type"`
	EntityID   pgtype.UUID        `json:"entity_id"`
	Reason     string             `json:"reason"`
	Status     string             `json:"status"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type University struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	Name        string             `json:"name"`
	Type        string             `json:"type"`
	Province    string             `json:"province"`
	Description pgtype.Text        `json:"description"`
	LogoUrl     pgtype.Text        `json:"logo_url"`
	Website     pgtype.Text        `json:"website"`
	Email       pgtype.Text        `json:"email"`
	Phone       pgtype.Text        `json:"phone"`
	Verified    bool               `json:"verified"`
	VerifiedAt  pgtype.Timestamptz `json:"verified_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	Name            string             `json:"name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
