// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID             pgtype.UUID        `json:"id"`
	Slug           string             `json:"slug"`
	Title          string             `json:"title"`
	Excerpt        pgtype.Text        `json:"excerpt"`
	Content        string             `json:"content"`
	ContentJson    []byte             `json:"content_json"`
	CoverImageUrl  pgtype.Text        `json:"cover_image_url"`
	Type           string             `json:"type"`
	Status         string             `json:"status"`
	SourceName     pgtype.Text        `json:"source_name"`
	SourceUrl      pgtype.Text        `json:"source_url"`
	SeoTitle       pgtype.Text        `json:"seo_title"`
	SeoDescription pgtype.Text        `json:"seo_description"`
	IsFeatured     bool               `json:"is_featured"`
	AuthorID       pgtype.UUID        `json:"author_id"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type AuthActionToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Purpose    string             `json:"purpose"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Course struct {
	ID                pgtype.UUID        `json:"id"`
	Slug              string             `json:"slug"`
	UniversityID      pgtype.UUID        `json:"university_id"`
	Name              string             `json:"name"`
	Area              string             `json:"area"`
	Level             string             `json:"level"`
	Regime            string             `json:"regime"`
	DurationYears     pgtype.Int4        `json:"duration_years"`
	AnnualFee         pgtype.Numeric     `json:"annual_fee"`
	EntryRequirements pgtype.Text        `json:"entry_requirements"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type MentorProfile struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Headline     string             `json:"headline"`
	Bio          string             `json:"bio"`
	Expertise    string             `json:"expertise"`
	Availability pgtype.Text        `json:"availability"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type MentorshipSession struct {
	ID          pgtype.UUID        `json:"id"`
	MentorID    pgtype.UUID        `json:"mentor_id"`
	RequesterID pgtype.UUID        `json:"requester_id"`
	Message     string             `json:"message"`
	Status      string             `json:"status"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Opportunity struct {
	ID                 pgtype.UUID        `json:"id"`
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	Type               string             `json:"type"`
	EntityName         string             `json:"entity_name"`
	Description        string             `json:"description"`
	Requirements       pgtype.Text        `json:"requirements"`
	Deadline           pgtype.Timestamptz `json:"deadline"`
	ApplyUrl           pgtype.Text        `json:"apply_url"`
	ExternalUrlLabel   pgtype.Text        `json:"external_url_label"`
	Country            string             `json:"country"`
	Location           pgtype.Text        `json:"location"`
	IsRemote           bool               `json:"is_remote"`
	Language           pgtype.Text        `json:"language"`
	Area               pgtype.Text        `json:"area"`
	HeroImageUrl       pgtype.Text        `json:"hero_image_url"`
	ProviderLogoUrl    pgtype.Text        `json:"provider_logo_url"`
	AmountMin          pgtype.Numeric     `json:"amount_min"`
	AmountMax          pgtype.Numeric     `json:"amount_max"`
	AmountCurrency     string             `json:"amount_currency"`
	Coverage           []string           `json:"coverage"`
	Eligibility        pgtype.Text        `json:"eligibility"`
	ApplicationProcess pgtype.Text        `json:"application_process"`
	DegreeLevel        pgtype.Text        `json:"degree_level"`
	ProgramArea        pgtype.Text        `json:"program_area"`
	IsActive           bool               `json:"is_active"`
	PublishedBy        pgtype.UUID        `json:"published_by"`
	Verified           bool               `json:"verified"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type RefreshToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Report struct {
	ID              pgtype.UUID        `json:"id"`
	ReporterID      pgtype.UUID        `json:"reporter_id"`
	EntityType      string             `json:"entity_type"`
	EntityID        pgtype.UUID        `json:"entity_id"`
	Reason          string             `json:"reason"`
	Status          string             `json:"status"`
	ReviewedBy      pgtype.UUID        `json:"reviewed_by"`
	ModerationNotes pgtype.Text        `json:"moderation_notes"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type University struct {
	ID                 pgtype.UUID        `json:"id"`
	Slug               string             `json:"slug"`
	Name               string             `json:"name"`
	Type               string             `json:"type"`
	Province           string             `json:"province"`
	City               pgtype.Text        `json:"city"`
	Country            string             `json:"country"`
	Description        pgtype.Text        `json:"description"`
	LogoUrl            pgtype.Text        `json:"logo_url"`
	CampusImageUrl     pgtype.Text        `json:"campus_image_url"`
	Website            pgtype.Text        `json:"website"`
	Email              pgtype.Text        `json:"email"`
	Phone              pgtype.Text        `json:"phone"`
	FoundedYear        pgtype.Int4        `json:"founded_year"`
	Address            pgtype.Text        `json:"address"`
	MapUrl             pgtype.Text        `json:"map_url"`
	AcademicCalendar   pgtype.Text        `json:"academic_calendar"`
	StudentCount       pgtype.Int4        `json:"student_count"`
	AdmissionsDeadline pgtype.Date        `json:"admissions_deadline"`
	Tags               []string           `json:"tags"`
	Verified           bool               `json:"verified"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	CreatedBy          pgtype.UUID        `json:"created_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type UniversityFee struct {
	ID           pgtype.UUID        `json:"id"`
	UniversityID pgtype.UUID        `json:"university_id"`
	Label        string             `json:"label"`
	Value        string             `json:"value"`
	SortOrder    int32              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type UniversityScholarship struct {
	ID           pgtype.UUID        `json:"id"`
	UniversityID pgtype.UUID        `json:"university_id"`
	Name         string             `json:"name"`
	Amount       pgtype.Text        `json:"amount"`
	Status       string             `json:"status"`
	SortOrder    int32              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID              pgtype.UUID        `json:"id"`
	Email           string             `json:"email"`
	PasswordHash    string             `json:"password_hash"`
	Role            string             `json:"role"`
	Name            string             `json:"name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	EmailVerifiedAt pgtype.Timestamptz `json:"email_verified_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
