// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: opportunities.sql

package queries

import (
	"context"
)

const countOpportunities = `-- name: CountOpportunities :one
SELECT COUNT(*)
FROM opportunities
WHERE deleted_at IS NULL
`

func (q *Queries) CountOpportunities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpportunities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOpportunityBySlug = `-- name: GetOpportunityBySlug :one
SELECT id, slug, title, type, entity_name, description, requirements, deadline, apply_url, country, language, area, is_active, published_by, verified, created_at, updated_at, deleted_at
FROM opportunities
WHERE slug = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetOpportunityBySlug(ctx context.Context, slug string) (Opportunity, error) {
	row := q.db.QueryRow(ctx, getOpportunityBySlug, slug)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.EntityName,
		&i.Description,
		&i.Requirements,
		&i.Deadline,
		&i.ApplyUrl,
		&i.Country,
		&i.Language,
		&i.Area,
		&i.IsActive,
		&i.PublishedBy,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOpportunities = `-- name: ListOpportunities :many
SELECT id, slug, title, type, entity_name, description, requirements, deadline, apply_url, country, language, area, is_active, published_by, verified, created_at, updated_at, deleted_at
FROM opportunities
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOpportunitiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOpportunities(ctx context.Context, arg ListOpportunitiesParams) ([]Opportunity, error) {
	rows, err := q.db.Query(ctx, listOpportunities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Opportunity{}
	for rows.Next() {
		var i Opportunity
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Type,
			&i.EntityName,
			&i.Description,
			&i.Requirements,
			&i.Deadline,
			&i.ApplyUrl,
			&i.Country,
			&i.Language,
			&i.Area,
			&i.IsActive,
			&i.PublishedBy,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
