// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: opportunities.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCMSOpportunities = `-- name: CountCMSOpportunities :one
SELECT COUNT(*)
FROM opportunities
WHERE deleted_at IS NULL
`

func (q *Queries) CountCMSOpportunities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCMSOpportunities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOpportunities = `-- name: CountOpportunities :one
SELECT COUNT(*)
FROM opportunities
WHERE deleted_at IS NULL
`

func (q *Queries) CountOpportunities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOpportunities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOpportunity = `-- name: CreateOpportunity :one
INSERT INTO opportunities (
  slug,
  title,
  type,
  entity_name,
  description,
  requirements,
  deadline,
  apply_url,
  external_url_label,
  country,
  location,
  is_remote,
  language,
  area,
  hero_image_url,
  provider_logo_url,
  amount_min,
  amount_max,
  amount_currency,
  coverage,
  eligibility,
  application_process,
  degree_level,
  program_area,
  is_active,
  published_by,
  verified
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22,
  $23,
  $24,
  $25,
  $26,
  $27
)
RETURNING id, slug, title, type, entity_name, description, requirements, deadline, apply_url, external_url_label, country, location, is_remote, language, area, hero_image_url, provider_logo_url, amount_min, amount_max, amount_currency, coverage, eligibility, application_process, degree_level, program_area, is_active, published_by, verified, created_at, updated_at, deleted_at
`

type CreateOpportunityParams struct {
	Slug               string             `json:"slug"`
	Title              string             `json:"title"`
	Type               string             `json:"type"`
	EntityName         string             `json:"entity_name"`
	Description        string             `json:"description"`
	Requirements       pgtype.Text        `json:"requirements"`
	Deadline           pgtype.Timestamptz `json:"deadline"`
	ApplyUrl           pgtype.Text        `json:"apply_url"`
	ExternalUrlLabel   pgtype.Text        `json:"external_url_label"`
	Country            string             `json:"country"`
	Location           pgtype.Text        `json:"location"`
	IsRemote           bool               `json:"is_remote"`
	Language           pgtype.Text        `json:"language"`
	Area               pgtype.Text        `json:"area"`
	HeroImageUrl       pgtype.Text        `json:"hero_image_url"`
	ProviderLogoUrl    pgtype.Text        `json:"provider_logo_url"`
	AmountMin          pgtype.Numeric     `json:"amount_min"`
	AmountMax          pgtype.Numeric     `json:"amount_max"`
	AmountCurrency     string             `json:"amount_currency"`
	Coverage           []string           `json:"coverage"`
	Eligibility        pgtype.Text        `json:"eligibility"`
	ApplicationProcess pgtype.Text        `json:"application_process"`
	DegreeLevel        pgtype.Text        `json:"degree_level"`
	ProgramArea        pgtype.Text        `json:"program_area"`
	IsActive           bool               `json:"is_active"`
	PublishedBy        pgtype.UUID        `json:"published_by"`
	Verified           bool               `json:"verified"`
}

func (q *Queries) CreateOpportunity(ctx context.Context, arg CreateOpportunityParams) (Opportunity, error) {
	row := q.db.QueryRow(ctx, createOpportunity,
		arg.Slug,
		arg.Title,
		arg.Type,
		arg.EntityName,
		arg.Description,
		arg.Requirements,
		arg.Deadline,
		arg.ApplyUrl,
		arg.ExternalUrlLabel,
		arg.Country,
		arg.Location,
		arg.IsRemote,
		arg.Language,
		arg.Area,
		arg.HeroImageUrl,
		arg.ProviderLogoUrl,
		arg.AmountMin,
		arg.AmountMax,
		arg.AmountCurrency,
		arg.Coverage,
		arg.Eligibility,
		arg.ApplicationProcess,
		arg.DegreeLevel,
		arg.ProgramArea,
		arg.IsActive,
		arg.PublishedBy,
		arg.Verified,
	)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.EntityName,
		&i.Description,
		&i.Requirements,
		&i.Deadline,
		&i.ApplyUrl,
		&i.ExternalUrlLabel,
		&i.Country,
		&i.Location,
		&i.IsRemote,
		&i.Language,
		&i.Area,
		&i.HeroImageUrl,
		&i.ProviderLogoUrl,
		&i.AmountMin,
		&i.AmountMax,
		&i.AmountCurrency,
		&i.Coverage,
		&i.Eligibility,
		&i.ApplicationProcess,
		&i.DegreeLevel,
		&i.ProgramArea,
		&i.IsActive,
		&i.PublishedBy,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deactivateOpportunity = `-- name: DeactivateOpportunity :one
UPDATE opportunities
SET
  is_active = FALSE
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, slug, title, type, entity_name, description, requirements, deadline, apply_url, external_url_label, country, location, is_remote, language, area, hero_image_url, provider_logo_url, amount_min, amount_max, amount_currency, coverage, eligibility, application_process, degree_level, program_area, is_active, published_by, verified, created_at, updated_at, deleted_at
`

func (q *Queries) DeactivateOpportunity(ctx context.Context, id pgtype.UUID) (Opportunity, error) {
	row := q.db.QueryRow(ctx, deactivateOpportunity, id)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.EntityName,
		&i.Description,
		&i.Requirements,
		&i.Deadline,
		&i.ApplyUrl,
		&i.ExternalUrlLabel,
		&i.Country,
		&i.Location,
		&i.IsRemote,
		&i.Language,
		&i.Area,
		&i.HeroImageUrl,
		&i.ProviderLogoUrl,
		&i.AmountMin,
		&i.AmountMax,
		&i.AmountCurrency,
		&i.Coverage,
		&i.Eligibility,
		&i.ApplicationProcess,
		&i.DegreeLevel,
		&i.ProgramArea,
		&i.IsActive,
		&i.PublishedBy,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOpportunityByID = `-- name: GetOpportunityByID :one
SELECT id, slug, title, type, entity_name, description, requirements, deadline, apply_url, external_url_label, country, location, is_remote, language, area, hero_image_url, provider_logo_url, amount_min, amount_max, amount_currency, coverage, eligibility, application_process, degree_level, program_area, is_active, published_by, verified, created_at, updated_at, deleted_at
FROM opportunities
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetOpportunityByID(ctx context.Context, id pgtype.UUID) (Opportunity, error) {
	row := q.db.QueryRow(ctx, getOpportunityByID, id)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.EntityName,
		&i.Description,
		&i.Requirements,
		&i.Deadline,
		&i.ApplyUrl,
		&i.ExternalUrlLabel,
		&i.Country,
		&i.Location,
		&i.IsRemote,
		&i.Language,
		&i.Area,
		&i.HeroImageUrl,
		&i.ProviderLogoUrl,
		&i.AmountMin,
		&i.AmountMax,
		&i.AmountCurrency,
		&i.Coverage,
		&i.Eligibility,
		&i.ApplicationProcess,
		&i.DegreeLevel,
		&i.ProgramArea,
		&i.IsActive,
		&i.PublishedBy,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getOpportunityBySlug = `-- name: GetOpportunityBySlug :one
SELECT id, slug, title, type, entity_name, description, requirements, deadline, apply_url, external_url_label, country, location, is_remote, language, area, hero_image_url, provider_logo_url, amount_min, amount_max, amount_currency, coverage, eligibility, application_process, degree_level, program_area, is_active, published_by, verified, created_at, updated_at, deleted_at
FROM opportunities
WHERE slug = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetOpportunityBySlug(ctx context.Context, slug string) (Opportunity, error) {
	row := q.db.QueryRow(ctx, getOpportunityBySlug, slug)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.EntityName,
		&i.Description,
		&i.Requirements,
		&i.Deadline,
		&i.ApplyUrl,
		&i.ExternalUrlLabel,
		&i.Country,
		&i.Location,
		&i.IsRemote,
		&i.Language,
		&i.Area,
		&i.HeroImageUrl,
		&i.ProviderLogoUrl,
		&i.AmountMin,
		&i.AmountMax,
		&i.AmountCurrency,
		&i.Coverage,
		&i.Eligibility,
		&i.ApplicationProcess,
		&i.DegreeLevel,
		&i.ProgramArea,
		&i.IsActive,
		&i.PublishedBy,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCMSOpportunities = `-- name: ListCMSOpportunities :many
SELECT id, slug, title, type, entity_name, description, requirements, deadline, apply_url, external_url_label, country, location, is_remote, language, area, hero_image_url, provider_logo_url, amount_min, amount_max, amount_currency, coverage, eligibility, application_process, degree_level, program_area, is_active, published_by, verified, created_at, updated_at, deleted_at
FROM opportunities
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCMSOpportunitiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCMSOpportunities(ctx context.Context, arg ListCMSOpportunitiesParams) ([]Opportunity, error) {
	rows, err := q.db.Query(ctx, listCMSOpportunities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Opportunity{}
	for rows.Next() {
		var i Opportunity
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Type,
			&i.EntityName,
			&i.Description,
			&i.Requirements,
			&i.Deadline,
			&i.ApplyUrl,
			&i.ExternalUrlLabel,
			&i.Country,
			&i.Location,
			&i.IsRemote,
			&i.Language,
			&i.Area,
			&i.HeroImageUrl,
			&i.ProviderLogoUrl,
			&i.AmountMin,
			&i.AmountMax,
			&i.AmountCurrency,
			&i.Coverage,
			&i.Eligibility,
			&i.ApplicationProcess,
			&i.DegreeLevel,
			&i.ProgramArea,
			&i.IsActive,
			&i.PublishedBy,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpportunities = `-- name: ListOpportunities :many
SELECT id, slug, title, type, entity_name, description, requirements, deadline, apply_url, external_url_label, country, location, is_remote, language, area, hero_image_url, provider_logo_url, amount_min, amount_max, amount_currency, coverage, eligibility, application_process, degree_level, program_area, is_active, published_by, verified, created_at, updated_at, deleted_at
FROM opportunities
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListOpportunitiesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOpportunities(ctx context.Context, arg ListOpportunitiesParams) ([]Opportunity, error) {
	rows, err := q.db.Query(ctx, listOpportunities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Opportunity{}
	for rows.Next() {
		var i Opportunity
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Type,
			&i.EntityName,
			&i.Description,
			&i.Requirements,
			&i.Deadline,
			&i.ApplyUrl,
			&i.ExternalUrlLabel,
			&i.Country,
			&i.Location,
			&i.IsRemote,
			&i.Language,
			&i.Area,
			&i.HeroImageUrl,
			&i.ProviderLogoUrl,
			&i.AmountMin,
			&i.AmountMax,
			&i.AmountCurrency,
			&i.Coverage,
			&i.Eligibility,
			&i.ApplicationProcess,
			&i.DegreeLevel,
			&i.ProgramArea,
			&i.IsActive,
			&i.PublishedBy,
			&i.Verified,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectOpportunity = `-- name: RejectOpportunity :one
UPDATE opportunities
SET
  verified = FALSE,
  is_active = FALSE
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, slug, title, type, entity_name, description, requirements, deadline, apply_url, external_url_label, country, location, is_remote, language, area, hero_image_url, provider_logo_url, amount_min, amount_max, amount_currency, coverage, eligibility, application_process, degree_level, program_area, is_active, published_by, verified, created_at, updated_at, deleted_at
`

func (q *Queries) RejectOpportunity(ctx context.Context, id pgtype.UUID) (Opportunity, error) {
	row := q.db.QueryRow(ctx, rejectOpportunity, id)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.EntityName,
		&i.Description,
		&i.Requirements,
		&i.Deadline,
		&i.ApplyUrl,
		&i.ExternalUrlLabel,
		&i.Country,
		&i.Location,
		&i.IsRemote,
		&i.Language,
		&i.Area,
		&i.HeroImageUrl,
		&i.ProviderLogoUrl,
		&i.AmountMin,
		&i.AmountMax,
		&i.AmountCurrency,
		&i.Coverage,
		&i.Eligibility,
		&i.ApplicationProcess,
		&i.DegreeLevel,
		&i.ProgramArea,
		&i.IsActive,
		&i.PublishedBy,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateOpportunity = `-- name: UpdateOpportunity :one
UPDATE opportunities
SET
  title = $2,
  type = $3,
  entity_name = $4,
  description = $5,
  requirements = $6,
  deadline = $7,
  apply_url = $8,
  external_url_label = $9,
  country = $10,
  location = $11,
  is_remote = $12,
  language = $13,
  area = $14,
  hero_image_url = $15,
  provider_logo_url = $16,
  amount_min = $17,
  amount_max = $18,
  amount_currency = $19,
  coverage = $20,
  eligibility = $21,
  application_process = $22,
  degree_level = $23,
  program_area = $24
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, slug, title, type, entity_name, description, requirements, deadline, apply_url, external_url_label, country, location, is_remote, language, area, hero_image_url, provider_logo_url, amount_min, amount_max, amount_currency, coverage, eligibility, application_process, degree_level, program_area, is_active, published_by, verified, created_at, updated_at, deleted_at
`

type UpdateOpportunityParams struct {
	ID                 pgtype.UUID        `json:"id"`
	Title              string             `json:"title"`
	Type               string             `json:"type"`
	EntityName         string             `json:"entity_name"`
	Description        string             `json:"description"`
	Requirements       pgtype.Text        `json:"requirements"`
	Deadline           pgtype.Timestamptz `json:"deadline"`
	ApplyUrl           pgtype.Text        `json:"apply_url"`
	ExternalUrlLabel   pgtype.Text        `json:"external_url_label"`
	Country            string             `json:"country"`
	Location           pgtype.Text        `json:"location"`
	IsRemote           bool               `json:"is_remote"`
	Language           pgtype.Text        `json:"language"`
	Area               pgtype.Text        `json:"area"`
	HeroImageUrl       pgtype.Text        `json:"hero_image_url"`
	ProviderLogoUrl    pgtype.Text        `json:"provider_logo_url"`
	AmountMin          pgtype.Numeric     `json:"amount_min"`
	AmountMax          pgtype.Numeric     `json:"amount_max"`
	AmountCurrency     string             `json:"amount_currency"`
	Coverage           []string           `json:"coverage"`
	Eligibility        pgtype.Text        `json:"eligibility"`
	ApplicationProcess pgtype.Text        `json:"application_process"`
	DegreeLevel        pgtype.Text        `json:"degree_level"`
	ProgramArea        pgtype.Text        `json:"program_area"`
}

func (q *Queries) UpdateOpportunity(ctx context.Context, arg UpdateOpportunityParams) (Opportunity, error) {
	row := q.db.QueryRow(ctx, updateOpportunity,
		arg.ID,
		arg.Title,
		arg.Type,
		arg.EntityName,
		arg.Description,
		arg.Requirements,
		arg.Deadline,
		arg.ApplyUrl,
		arg.ExternalUrlLabel,
		arg.Country,
		arg.Location,
		arg.IsRemote,
		arg.Language,
		arg.Area,
		arg.HeroImageUrl,
		arg.ProviderLogoUrl,
		arg.AmountMin,
		arg.AmountMax,
		arg.AmountCurrency,
		arg.Coverage,
		arg.Eligibility,
		arg.ApplicationProcess,
		arg.DegreeLevel,
		arg.ProgramArea,
	)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.EntityName,
		&i.Description,
		&i.Requirements,
		&i.Deadline,
		&i.ApplyUrl,
		&i.ExternalUrlLabel,
		&i.Country,
		&i.Location,
		&i.IsRemote,
		&i.Language,
		&i.Area,
		&i.HeroImageUrl,
		&i.ProviderLogoUrl,
		&i.AmountMin,
		&i.AmountMax,
		&i.AmountCurrency,
		&i.Coverage,
		&i.Eligibility,
		&i.ApplicationProcess,
		&i.DegreeLevel,
		&i.ProgramArea,
		&i.IsActive,
		&i.PublishedBy,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const verifyOpportunity = `-- name: VerifyOpportunity :one
UPDATE opportunities
SET
  verified = TRUE,
  is_active = TRUE
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, slug, title, type, entity_name, description, requirements, deadline, apply_url, external_url_label, country, location, is_remote, language, area, hero_image_url, provider_logo_url, amount_min, amount_max, amount_currency, coverage, eligibility, application_process, degree_level, program_area, is_active, published_by, verified, created_at, updated_at, deleted_at
`

func (q *Queries) VerifyOpportunity(ctx context.Context, id pgtype.UUID) (Opportunity, error) {
	row := q.db.QueryRow(ctx, verifyOpportunity, id)
	var i Opportunity
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Type,
		&i.EntityName,
		&i.Description,
		&i.Requirements,
		&i.Deadline,
		&i.ApplyUrl,
		&i.ExternalUrlLabel,
		&i.Country,
		&i.Location,
		&i.IsRemote,
		&i.Language,
		&i.Area,
		&i.HeroImageUrl,
		&i.ProviderLogoUrl,
		&i.AmountMin,
		&i.AmountMax,
		&i.AmountCurrency,
		&i.Coverage,
		&i.Eligibility,
		&i.ApplicationProcess,
		&i.DegreeLevel,
		&i.ProgramArea,
		&i.IsActive,
		&i.PublishedBy,
		&i.Verified,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
