// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCourses(ctx context.Context) (int64, error)
	CountMentors(ctx context.Context) (int64, error)
	CountOpportunities(ctx context.Context) (int64, error)
	CountUniversities(ctx context.Context) (int64, error)
	CreateMentorshipSession(ctx context.Context, arg CreateMentorshipSessionParams) (MentorshipSession, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetCourseBySlug(ctx context.Context, slug string) (Course, error)
	GetMentorByID(ctx context.Context, userID pgtype.UUID) (GetMentorByIDRow, error)
	GetOpportunityBySlug(ctx context.Context, slug string) (Opportunity, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUniversityBySlug(ctx context.Context, slug string) (University, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error)
	ListMentors(ctx context.Context, arg ListMentorsParams) ([]ListMentorsRow, error)
	ListOpportunities(ctx context.Context, arg ListOpportunitiesParams) ([]Opportunity, error)
	ListUniversities(ctx context.Context, arg ListUniversitiesParams) ([]University, error)
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
