// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ConsumeAuthActionToken(ctx context.Context, id pgtype.UUID) error
	CountArticles(ctx context.Context) (int64, error)
	CountCourses(ctx context.Context) (int64, error)
	CountMentors(ctx context.Context) (int64, error)
	CountOpportunities(ctx context.Context) (int64, error)
	CountReports(ctx context.Context) (int64, error)
	CountUniversities(ctx context.Context) (int64, error)
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	CreateAuthActionToken(ctx context.Context, arg CreateAuthActionTokenParams) (AuthActionToken, error)
	CreateMentorshipSession(ctx context.Context, arg CreateMentorshipSessionParams) (MentorshipSession, error)
	CreateOpportunity(ctx context.Context, arg CreateOpportunityParams) (Opportunity, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetArticleByID(ctx context.Context, id pgtype.UUID) (Article, error)
	GetArticleBySlug(ctx context.Context, slug string) (Article, error)
	GetAuthActionTokenByHash(ctx context.Context, arg GetAuthActionTokenByHashParams) (AuthActionToken, error)
	GetCourseBySlug(ctx context.Context, slug string) (Course, error)
	GetMentorByID(ctx context.Context, userID pgtype.UUID) (GetMentorByIDRow, error)
	GetOpportunityByID(ctx context.Context, id pgtype.UUID) (Opportunity, error)
	GetOpportunityBySlug(ctx context.Context, slug string) (Opportunity, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetReportByID(ctx context.Context, id pgtype.UUID) (Report, error)
	GetUniversityBySlug(ctx context.Context, slug string) (University, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error)
	ListCourses(ctx context.Context, arg ListCoursesParams) ([]Course, error)
	ListMentors(ctx context.Context, arg ListMentorsParams) ([]ListMentorsRow, error)
	ListOpportunities(ctx context.Context, arg ListOpportunitiesParams) ([]Opportunity, error)
	ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error)
	ListUniversities(ctx context.Context, arg ListUniversitiesParams) ([]University, error)
	MarkUserEmailVerified(ctx context.Context, id pgtype.UUID) (User, error)
	PublishArticle(ctx context.Context, id pgtype.UUID) (Article, error)
	RevokeAllRefreshTokensByUser(ctx context.Context, userID pgtype.UUID) error
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	UpdateArticle(ctx context.Context, arg UpdateArticleParams) (Article, error)
	UpdateOpportunity(ctx context.Context, arg UpdateOpportunityParams) (Opportunity, error)
	UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
	UpdateUserPasswordByID(ctx context.Context, arg UpdateUserPasswordByIDParams) (User, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	VerifyOpportunity(ctx context.Context, id pgtype.UUID) (Opportunity, error)
}

var _ Querier = (*Queries)(nil)
