// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countReports = `-- name: CountReports :one
SELECT COUNT(*)
FROM reports
WHERE deleted_at IS NULL
`

func (q *Queries) CountReports(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countReports)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (
  reporter_id,
  entity_type,
  entity_id,
  reason,
  status,
  resolved_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  'pending',
  NULL
)
RETURNING id, reporter_id, entity_type, entity_id, reason, status, resolved_at, created_at, updated_at, deleted_at
`

type CreateReportParams struct {
	ReporterID pgtype.UUID `json:"reporter_id"`
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Reason     string      `json:"reason"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterID,
		arg.EntityType,
		arg.EntityID,
		arg.Reason,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.EntityType,
		&i.EntityID,
		&i.Reason,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, reporter_id, entity_type, entity_id, reason, status, resolved_at, created_at, updated_at, deleted_at
FROM reports
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetReportByID(ctx context.Context, id pgtype.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.EntityType,
		&i.EntityID,
		&i.Reason,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listReports = `-- name: ListReports :many
SELECT id, reporter_id, entity_type, entity_id, reason, status, resolved_at, created_at, updated_at, deleted_at
FROM reports
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListReportsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReports, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.EntityType,
			&i.EntityID,
			&i.Reason,
			&i.Status,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportStatus = `-- name: UpdateReportStatus :one
UPDATE reports
SET
  status = $2,
  resolved_at = CASE WHEN $2 IN ('resolved', 'dismissed') THEN NOW() ELSE NULL END
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, reporter_id, entity_type, entity_id, reason, status, resolved_at, created_at, updated_at, deleted_at
`

type UpdateReportStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateReportStatus(ctx context.Context, arg UpdateReportStatusParams) (Report, error) {
	row := q.db.QueryRow(ctx, updateReportStatus, arg.ID, arg.Status)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.EntityType,
		&i.EntityID,
		&i.Reason,
		&i.Status,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
